# Generated by Django 4.2.2 on 2023-07-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_review_alter_like_review_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='movies',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='review',
            new_name='movies',
        ),
    ]
