# Generated by Django 4.2.2 on 2023-07-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_is_favorite'),
        ('genres', '0002_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
